db:
  password: "${DB_PASSWORD}"
  name: "${DB_NAME}"
  user: "${DB_USER}"

ingress:
  enabled: true
  className: "alb"
  host: ""
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: "${SUBNET_1}, ${SUBNET_2}"
    alb.ingress.kubernetes.io/security-groups: "${ALB_SG_ID}"
    alb.ingress.kubernetes.io/healthcheck-port: "8080"
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
