apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.db.name }}
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
  DATABASE_URL: "postgresql://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ .Release.Name }}-db-service:5432/{{ .Values.db.name }}"
